# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174f346efa2c680e4c201cdb15e06c35ef7aad06f4e941bf1d6ba7783a65aec34ed6d76cbad9aa38d2fd39f764f68e3dda828bc2cca1d07ee253750b219beb7e

test:
  secret_key_base: a401a1fcead3383d1d150dd7baf9e78b2bb2b28a72ab59b7bb158106ea9df52cf3be5f326a5ab83bdae716eb93387debaec45454d29a385274ef0d0c3a977150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
